name = "Venom SMP"
author = "vos6434, bananasov"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb01a523c64515e2e4ad649826baca21ff9099cbd6cfa9bc6eae40dbd16a3300"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
